import { nanoid } from 'nanoid';

import { Recipe } from 'services/recipes';

export const pancakes: Recipe = {
  id: nanoid(),
  name: 'Oryginalne Amerykańskie Pancakes\'y',
  description: 'Oryginalny przepis na amerykańskie placuszki zwane Pancakes\'ami . Delikatne, złociste, rozpływające się w ustach danie serwowane głównie na śniadanie. Pancakes\'y przeważają w wersji na słodko, jako deser, a w Polsce myślę, że nieraz wystąpią na stole jako smaczny i szybki obiad.',
  image: 'https://3.bp.blogspot.com/-TsSjrA-5opI/UzASiu3PGbI/AAAAAAAADZ0/0viA-MaSTiY/s1600/Pancakes+5.jpg',
  ingredients: [
    { text: '135 g mąki pszennej' },
    { text: '1 łyżeczka proszku do pieczenia' },
    { text: '0.5 łyżeczki soli' },
    { text: '2 łyżki cukru pudru' },
    { text: '130 ml mleka' },
    { text: '1 duże jajko (roztrzepane)' },
    { text: '2 łyżki roztopionego masła + dodatkowo do smażenia' },
  ],
  instructions: [
    { text: 'Mąkę, proszek, cukier puder i sól mieszamy ze sobą.' },
    { text: 'Jajko roztrzepujemy z mlekiem i dodajemy do reszty - łączymy składniki.' },
    { text: 'Na końcu dodajemy roztopione masło - mieszamy do otrzymania gładkiej konsystencji.' },
    { text: 'Placuszki smażymy na niewielkiej ilości masła na złoto-brązowy kolor z obu stron (pancakes\'y są gotowe do przewrócenia gdy na ich powierzchni pojawiają się pęcherzyki powietrza).' },
    { text: 'Podajemy z syropem klonowym, miodem lub innym ulubionym dodatkiem.' },
  ],
  prepTime: 20,
  url: 'http://www.slodkastrona.com/2014/03/oryginalne-amerykanskie-pancakesy.html',
  tags: ['śniadanie', 'na słodko'],
  servings: 10,
  calories: 1750,
};

export const pierniczki: Recipe = {
  id: nanoid(),
  name: 'Pierniczki z lukrem',
  description: 'Tradycyjne pierniczki oblane pysznym lukrem – gwarantują niesamowicie świąteczną atmosferę.',
  image: 'https://aniastarmach.pl/content/uploads/2016/12/pierniczki-z-lukrem-16-1200x630.jpg',
  ingredients: [
    { text: '300 g mąki pszennej + mąka do podsypywania ciasta podczas wałkowania' },
    { text: '150 ml miodu' },
    { text: '50 g cukru pudru' },
    { text: '50 g masła' },
    { text: '1 jajko' },
    { text: '1 łyżeczka proszku do pieczenia' },
    { text: '1 łyżeczka cukru waniliowego' },
    { text: '1 łyżka przyprawy do piernika (w składzie: cynamon, kardamon, imbir, anyż)' },
    { text: '2 łyżki kandyzowanej skórki pomarańczowej' },
    { text: '1 szklanka cukru pudru' },
    { text: '1 łyżkę soku z cytryny' },
  ],
  instructions: [
    { text: 'Skórkę pomarańczową bardzo drobno posiekaj.' },
    { text: 'Bardzo miękkie masło wymieszaj na stolnicy z mąką, cukrem pudrem i miodem. Dodaj proszek do pieczenia, jajko, przyprawy i posiekaną skórkę pomarańczową.' },
    { text: 'Ciasto szybko zagnieć i wsadź do lodówki na min. 30 minut.' },
    { text: 'Piekarnik rozgrzej do temperatury 180 stopni.' },
    { text: 'Wyjmij ciasto z lodówki i rozwałkuj dość grubo – około 0,5 cm (im cieńsze ciasto, tym twardsze pierniczki). Żeby się nie przyklejało do stolnicy podsypuj je mąką. Wykrawaj pierniczki.' },
    { text: 'Układaj je na blasze wyłożonej papierem do pieczenia i piecz przez ok. 10-12 minut.' },
    { text: 'Aby przygotować lukier, cukier puder przesiej do miski, dodaj sok z cytryny i wymieszaj. Całość podgrzej. Jeśli lukier będzie zbyt rzadki dodaj więcej cukru, jeśli zbyt gesty – soku. Gotowym lukrem dekoruj upieczone pierniczki.' },
  ],
  prepTime: 40,
  tags: [
    'boże narodzenie',
    'ciastka',
    'cukier puder',
    'impreza',
    'lukier',
    'mąka',
    'miód',
    'na słodko',
    'pierniczki',
    'piernik',
    'podwieczorek',
    'przyjęcie',
    'przyprawa do piernika',
  ],
  servings: 6,
  color: '#d9622e',
  url: 'https://aniastarmach.pl/przepis/pierniczki-z-lukrem/',
};

export const kurczak: Recipe = {
  id: nanoid(),
  name: 'Kurczak z gorgonzolą',
  ingredients: [
    { text: '500 g filetu z indyka lub kurczaka' },
    { text: '80 g cieniutkiego boczku (paczkowanego) lub szynki parmeńskiej / prosciutto crudo / szynki suszonej' },
    { text: '180 ml śmietanki 30%' },
    { text: '90 g sera gorgonzola' },
    { text: '1/2 łyżki posiekanej bazylii lub natki pietruszki' },
    { text: 'kilka pomidorków koktajlowych' },
  ],
  image: 'https://www.kwestiasmaku.com/sites/v123.kwestiasmaku.com/files/kurczak-z-gorgonzola-00.jpg',
  instructions: [
    { text: 'Mięso opłukać, osuszyć, przekroić poziomo na 2 cieńsze filety, następnie pokroić je na mniejszej wielkości kawałki. Rozbić tłuczkiem na grubość ok. 7 mm.' },
    { text: 'Doprawić solą (niezbyt dużo bo boczek/szynka jest słona) oraz pieprzem. Fileciki zawinąć w plasterki boczku lub szynki.' },
    { text: 'Rozgrzać patelnię z łyżką oliwy, rozprowadzić ją po całej patelni. Obsmażyć mięso z dwóch stron na większym ogniu aż boczek się lekko podtopi i zrumieni.' },
    { text: 'Zdjąć z patelni, wylać tłuszcz i wyczyścić patelnię ręcznikiem papierowym. Ustawić patelnię na średnim ogniu, wlać śmietankę, doprawić solą i pieprzem, dodać pokrojoną w kosteczkę gorgonzolę. Mieszając podgrzewać aż ser się roztopi.' },
    { text: 'Włożyć mięso i podgrzewać razem przez ok. 1 minutę, posypać bazylią lub natką.' },
  ],
  tags: [
    'hity kwestii smaku',
    'filety drobiowe',
    'szybki obiad',
    'dania główne',
    'kurczak',
    'indyk',
    'gorgonzola',
    'szynka parmeńska',
    'boczek',
  ],
  color: '#cb1c0b',
  url: 'https://www.kwestiasmaku.com/przepis/filety-drobiowe-w-sosie-z-gorgonzoli',
};

export const ramen: Recipe = {
  id: nanoid(),
  name: 'Ramen',
  ingredients: [
    { text: '1 kg kości wieprzowych' },
    { text: '1 kg kości drobiowych (np. korpus kurczaka, indyka)' },
    { text: '4 cebulki szalotki' },
    { text: '10 cm korzenia imbiru' },
    { text: 'pół główki czosnku' },
    { text: '2 marchewki' },
    { text: 'wodorosty/algi konbu - płat o wymiarach ok. 7 x 20 cm' },
    { text: 'ok. 80 - 100 ml japońskiego sosu sojowego (shoyu)' },
    { text: '80 ml sake (wino ryżowe)' },
    { text: 'wolno gotowana wieprzowina' },
    { text: '30 g suszonych grzybów shitake' },
    { text: '500 g świeżego makaronu ramen lub 220 g suszonego' },
    { text: 'dymka lub szczypiorek' },
    { text: '6 jajek' },
    { text: 'przyprawa shichimi togarashi' },
    { text: 'prasowane glony (sushi nori)' },
    { text: 'kiełki fasoli' },
    { text: '200 g bok choy (pak choy)' },
    { text: 'sezamowy olej chili' },
  ],
  image: 'https://www.kwestiasmaku.com/sites/v123.kwestiasmaku.com/files/ramen_00.jpg',
  instructions: [
    { text: 'Do dużego garnka włożyć kości wieprzowe i drobiowe. Całkowicie zalać je zimną wodą. Doprowadzić do wrzenia na dużym ogniu, następnie odcedzić, przepłukać zimną wodą i ponownie włożyć je do pustego garnka.' },
    { text: 'Cebulki obrać z zewnętrznych łusek, umyć. Cebulki i czosnek rozgnieść dla uwolnienia soku, dodać do garnka z mięsem. Dodać pokrojony na plastry imbir oraz obraną i pokrojoną na kilka części marchewkę. Dodać zgrubnie opłukany glon konbu i zalać całość zimną wodą (około 2 litry, do przykrycia składników).' },
    { text: 'Zagotować na dużym ogniu, wyjąć konbu (nie będzie potrzebne), usunąć z wierzchu szumowinę jeśli się pojawi. Ustawić garnek na minimalnym palniku, zmniejszyć ogień do minimum. Gotować pod uchyloną pokrywą przez około 6 godzin.' },
    { text: 'Po przestudzeniu wyjąć kości i przecedzić bulion przez sito. Ostudzić i odstawić do lodówki.' },
    { text: 'Dzień wcześniej namoczyć grzyby shitake: zalać ciepłą wodą i odstawić do namoczenia. Namoczone grzyby shitake pokroić i podsmażyć na oleju aż będą miękkie. Ugotować jajka (5 min. od zagotowania wody). Przygotować mięso wieprzowe (przepis).' },
    { text: 'Bulion przelać do garnka (wcześniej można zebrać część lub cały tłuszcz z wierzchu zimnej zupy). Dodać sos sojowy (na razie połowę ilości) oraz sake, zagotować, spróbować i w razie potrzeby dodawać stopniowo więcej sosu sojowego.' },
    { text: 'Do misek włożyć ugotowany makaron, wlać bulion, ułożyć grzyby shitake, plaster mięsa z pieczeni, przepołowione ugotowane jajko, kawałek prasowanych glonów, posypać dymką lub szczypiorkiem i doprawić przyprawą shichimi togarashi.' },
    { text: 'Można też dodać pak choi (pokrojony wzdłuż na szerokie paski i blanszowany), kiełki fasoli i skropić olejem sezamowym chili. Im więcej składników, tym lepiej ;) Ramen to zupa z dużą ilością makaronu i dodatków w porównaniu z samym bulionem.' },
  ],
  rating: 4.63,
  tags: [
    'kuchnia japońska',
    'ramen',
    'zupy',
    'zupy orientalne',
    'wieprzowina',
    'pak choi',
    'miso',
    'imbir',
    'sake',
    'glony',
    'kiełki fasoli mung',
    'makaron chow mein',
  ],
  color: '#f69307',
  url: 'https://www.kwestiasmaku.com/przepis/ramen-shoyu-z-wieprzowina',
};
